var tableauQuestion = [
    {   question : "Si vous conduisez à 80 km h, et vous approchez d'un quartier résidentiel, cela signifie que",
        propositionA : "Vous devez accélérer",
        propositionB : "Vous pouvez accélérer tant qu'il n'y a pas d'autres voitures",
        propositionC : "Vous devrez ralentir en avance",
        propositionD : "Vous pouvez maintenir votre vitesse",
        reponse : "C"},
		
    {   question : "En tournant à gauche sur un feu vert, vous voyez qu'un piéton est dans le passage à niveau. Qui a le droit de passage?",
        propositionA : "Les piétons, parce qu'ils peuvent traverser la route avec n'importe quelle feux",
        propositionB : "Votre véhicule parce que la lumière est verte",
        propositionC : "Le piéton, parce qu'elle traverse le feu vert",
        propositionD : "Votre véhicule, car les véhicules sont toujours au droit de passage",
        reponse : "C"},
		
    {   question : "Sauf publication, la vitesse maximale dans une zone résidentielle est de ___ km h.",
        propositionA : "50",
        propositionB : "55",
        propositionC : "240",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Avant chaque changement de voie, vous devriez.",
        propositionA : "Vérifiez vos rétroviseur ",
        propositionB : "Vérifiez vos points faibles",
        propositionC : "Vérifiez vos poches",
        propositionD : "Tout ce qui précède",
        reponse : "D"},
		
	{   question : "Quel taux d'alcoolémie est classé comme conduite en état d'ébriété?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Vous devez vous arrêter jusqu'à ce que tout véhicule d'urgence avec une sirène soit passé, à moins que:",
        propositionA : "Tu es pressé",
        propositionB : "Y'a ta femme qui t'attend ...",
        propositionC : "Vous êtes dans une zone scolaire",
        propositionD : "Vous êtes dans une intersection",
        reponse : "D"},
	
	{   question : "Le droit de passage doit être cédé aux véhicules d'urgence",
        propositionA : "De tout temps",
        propositionB : "Clignotant rouge, bleu ou blanc",
        propositionC : "En utilisant une sirène et des lumières clignotantes rouge, bleu ou blanc",
        propositionD : "Y'a un Poney",
        reponse : "C"},
		
	{   question : "Lequel des éléments suivants est autorisé lors du passage d'un autre véhicule?",
        propositionA : "Suivi de près",
        propositionB : "Quitter la route principale parcourue",
        propositionC : "Conduire du côté opposé de la route",
        propositionD : "lorsque que un camion bloque la circulation",
        reponse : "C"},
		
	{   question : "Vous conduisez sur une autoroute avec une limite de vitesse de 110 kmh. La plupart du trafic se déplace à 120 mph, donc vous devriez conduire pas plus vite que",
        propositionA : "80 kmh",
        propositionB : "10 kmh",
        propositionC : "25 kmh",
        propositionD : "110 kmh",
        reponse : "D"},
		
	{   question : "Lorsqu'il est passé par un autre véhicule, il est important de NE PAS",
        propositionA : "Ralentissez",
        propositionB : "Vérifiez vos miroirs",
        propositionC : "Regardez l'autre conducteur",
        propositionD : "Accélérer",
        reponse : "D"},
]
